services:
  database:
    image: postgres:latest
    container_name: promillezone-database
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: promillezone
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: promillezone-api
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/promillezone
      JWT_SECRET: TopSecretKey
    ports:
      - "3000:3000"

volumes:
  db-data:
